### ISSUE TITLE
美股期权学习笔记（四）

### ISSUE THREAD

**Issue by tinyhill666** [tangqiaoboy/tangqiaoboy.github.com#3]
https://blog.devtang.com/2020/03/22/option-learning-notes-3/
看不见

**Comment by tangqiaoboy** [comment]
正确地址是：https://blog.devtang.com/2020/03/21/option-learning-notes-3/


Tang Qiao



Tiny Hill <notifications@github.com> 于2020年11月16日周一 下午9:50写道：

**Comment by tinyhill666** [comment]
美股期权学习笔记（四）这个在其他三篇的链接不对。

**Comment by tangqiaoboy** [comment]
第四篇：https://blog.devtang.com/2020/03/22/option-learning-note-4/

Tang Qiao



唐巧 <tangqiaoboy@gmail.com> 于2020年11月18日周三 上午10:23写道：

**Comment by tangqiaoboy** [comment]
@qiushaoxi 链接已修复，多谢多谢！

**Comment by tinyhill666** [comment]
应该的，文章写的很好👍
